# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160720_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos',
            name='date',
        ),
        migrations.AddField(
            model_name='pos',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 8, 59, 0, 214169)),
        ),
        migrations.AddField(
            model_name='seasonaltrend',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 8, 59, 0, 215026)),
        ),
        migrations.AddField(
            model_name='seasonaltrend',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
