# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160720_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 8, 59, 53, 343309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='seasonaltrend',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 8, 59, 53, 344157, tzinfo=utc)),
        ),
    ]
