# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160720_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
