# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_timekeeper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 56, 19, 296527)),
        ),
        migrations.AlterField(
            model_name='master',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 56, 19, 296559)),
        ),
    ]
