# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160721_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 59, 25, 508309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='master',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 21, 12, 59, 25, 508377, tzinfo=utc)),
        ),
    ]
