# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160721_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
