# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160722_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='jan',
            field=models.CharField(max_length=256),
        ),
    ]
